backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/Home/Home.md"
        fields:
          - label: "Featured Image"
            name: "avatar"
            widget: "image"
          - label: "Banner"
            name: "banner"
            widget: list
            fields:
              - label: "Avatar"
                name: "avatar"
                widget: "image"
              - label: "text"
                name: "text"
                widget: "text"

          - label: "Card"
            name: "card"
            widget: list
            fields:
              - label: "Avatar"
                name: "avatar"
                widget: "image"
              - label: "text"
                name: "text"
                widget: "text"
